/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComputeInstancesRouteImport } from './routes/compute_.instances'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeInstancesRoute = ComputeInstancesRouteImport.update({
  id: '/compute_/instances',
  path: '/compute/instances',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/welcome': typeof WelcomeRoute
  '/compute/instances': typeof ComputeInstancesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/welcome': typeof WelcomeRoute
  '/compute/instances': typeof ComputeInstancesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/welcome': typeof WelcomeRoute
  '/compute_/instances': typeof ComputeInstancesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compute' | '/welcome' | '/compute/instances'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compute' | '/welcome' | '/compute/instances'
  id: '__root__' | '/' | '/compute' | '/welcome' | '/compute_/instances'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeRoute: typeof ComputeRoute
  WelcomeRoute: typeof WelcomeRoute
  ComputeInstancesRoute: typeof ComputeInstancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute_/instances': {
      id: '/compute_/instances'
      path: '/compute/instances'
      fullPath: '/compute/instances'
      preLoaderRoute: typeof ComputeInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeRoute: ComputeRoute,
  WelcomeRoute: WelcomeRoute,
  ComputeInstancesRoute: ComputeInstancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
